/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginConf.java
 *
 * Created on 18/03/2010, 03:19:38 PM
 */

package zolbee2;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author roberto
 */
public class LoginConf extends javax.swing.JFrame {


   //static String bd = "zolbee";
   //static String login = "roberto";
   //static String password = "roberto";
   static String url = Funciones.conectar;
   static String usuario;
   static String clave;
   static String id;


    /** Creates new form LoginConf */
    public LoginConf() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vUsuario = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        vClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zolbee2.Zolbee2App.class).getContext().getResourceMap(LoginConf.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        vUsuario.setText(resourceMap.getString("vUsuario.text")); // NOI18N
        vUsuario.setName("vUsuario"); // NOI18N

        bAceptar.setText(resourceMap.getString("bAceptar.text")); // NOI18N
        bAceptar.setName("bAceptar"); // NOI18N
        bAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loguearseBD(evt);
            }
        });
        bAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logueraseBDEnter(evt);
            }
        });

        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cerrarLoginConf(evt);
            }
        });
        bCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cerrarLoginConfEnter(evt);
            }
        });

        vClave.setText(resourceMap.getString("vClave.text")); // NOI18N
        vClave.setName("vClave"); // NOI18N
        vClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vClaveKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vClave)
                    .addComponent(vUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addComponent(bAceptar)
                .addGap(31, 31, 31)
                .addComponent(bCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loguearseBD(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguearseBD
        // TODO add your handling code here:
     loguearse();
     // fin de método loguearseBD
    }//GEN-LAST:event_loguearseBD

    private void cerrarLoginConf(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarLoginConf
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarLoginConf

    private void logueraseBDEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logueraseBDEnter
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
 
        loguearse();
        }

    }//GEN-LAST:event_logueraseBDEnter

    private void cerrarLoginConfEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cerrarLoginConfEnter
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
          this.dispose();
        }
    }//GEN-LAST:event_cerrarLoginConfEnter

    private void vClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vClaveKeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            loguearse();
         } // fin de if


    }//GEN-LAST:event_vClaveKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginConf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField vClave;
    private javax.swing.JTextField vUsuario;
    // End of variables declaration//GEN-END:variables


public void loguearse()
{

     //recibimos variables

         usuario = vUsuario.getText();
         clave = vClave.getText();


 Connection conn = null;

 try {
           Class.forName("com.mysql.jdbc.Connection");
           conn = (Connection) DriverManager.getConnection(url);
           if (conn != null)
           {
               System.out.println("Conexión a base de datos "+url+" ... Ok");
           }
       }
       catch(SQLException ex)
       {
           //JOptionPane.showMessageDialog(this,"Hubo un problema al intentar conectarse con la base de datos ..."+url);
           JOptionPane.showMessageDialog(this, "Hubo un problema al intentar conectarse con la base de datos ...", "Cuidado", JOptionPane.ERROR_MESSAGE);
           //System.out.println("Hubo un problema al intentar conectarse con la base de datos "+url);
       }
       catch(ClassNotFoundException ex)
       {
           System.out.println(ex);
       }

       Statement s;
          try
          {
           s =(Statement) conn.createStatement();

           System.out.println("Empezando a realizar la consulta");
           ResultSet rs = s.executeQuery("SELECT * FROM e_afiliadas WHERE usuario='"+usuario+"' AND clave='"+clave+"' ");
           rs.first();
           int cuantos = rs.getRow();

           //System.out.println(id);
           System.out.println(cuantos);


           if(cuantos != 0)
               {

                 id = rs.getString("ide_afiliadas");
                 System.out.println("Se logueo con exito");
                 SucursalesConf sucursalConf = new SucursalesConf();
                 //Menu f2 = new Menu();
                
                 sucursalConf.setLocationRelativeTo(null);
                 sucursalConf.getContentPane().setBackground(Color.decode("#7329ab"));
                 //lo hacemos visible
                 sucursalConf.setVisible(true);
                 //maximizamos la pantalla
                 //f1.setExtendedState(f1.getExtendedState()|f1.MAXIMIZED_BOTH);
                 this.dispose();

               }
                else
                {
                   JOptionPane.showMessageDialog(this,"Lo sentimos pero tu usuario y clave son incorrectas ...");
                }
        

       }
       catch (SQLException ex)
       {
           System.out.println("Hubo un problema al intentar obtener lo datos");
       }

} // fin del método loguearse





} // fin clase LoginConf
