/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 18/03/2010, 03:22:58 PM
 */

package zolbee2;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author roberto
 */
public class LoginReportes extends javax.swing.JFrame {
    static int opcion=0;

    /** Creates new form Login */
    public LoginReportes(int opc) {

        opcion= opc;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vUser = new javax.swing.JTextField();
        vPaswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zolbee2.Zolbee2App.class).getContext().getResourceMap(LoginReportes.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        bIngresar.setText(resourceMap.getString("bIngresar.text")); // NOI18N
        bIngresar.setName("bIngresar"); // NOI18N
        bIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loguearseSistemaM(evt);
            }
        });
        bIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loguearseSistemaE(evt);
            }
        });

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        vUser.setName("vUsr"); // NOI18N

        vPaswd.setText(resourceMap.getString("vPaswd.text")); // NOI18N
        vPaswd.setName("vPaswd"); // NOI18N
        vPaswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vPaswdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(bIngresar)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vPaswd)
                    .addComponent(vUser, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(451, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(vPaswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(65, 65, 65)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(bIngresar)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loguearseSistemaE(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loguearseSistemaE
        // TODO add your handling code here:

      if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
         loguearseSistema();
      }
    }//GEN-LAST:event_loguearseSistemaE

    private void loguearseSistemaM(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguearseSistemaM
        // TODO add your handling code here:
        loguearseSistema();
       
    }//GEN-LAST:event_loguearseSistemaM

    private void vPaswdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vPaswdKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            loguearseSistema();
         } // fin de if
    }//GEN-LAST:event_vPaswdKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginReportes(opcion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField vPaswd;
    private javax.swing.JTextField vUser;
    // End of variables declaration//GEN-END:variables


public void loguearseSistema() 
{
        String user = vUser.getText();
        String pass = vPaswd.getText();
        String clave = "zolbee";

        LeeFichero leerFichero = new LeeFichero ();
        Funciones funcion = new Funciones();
        Funciones funcion2 = new Funciones();
        leerFichero.leerFichero();
        funcion.EncriptCadena(clave,user);
        funcion2.EncriptCadena(clave, pass);
            

        if(funcion.encriptado.equals(leerFichero.vusuario) && funcion2.encriptado.equals(leerFichero.vpaswd))
        {

            switch(opcion)
            {
                case(1):
                     ReportesFecha fecha = new ReportesFecha ();
                     fecha.setLocationRelativeTo(null);
                     fecha.getContentPane().setBackground(Color.decode("#7329ab"));
                     fecha.setVisible(true);
                     break;
                case (2):
                     ReportesEmpleado empleado = new ReportesEmpleado ();
                     empleado.setLocationRelativeTo(null);
                     empleado.getContentPane().setBackground(Color.decode("#7329ab"));
                     empleado.setVisible(true);
                     break;
                case (3):
                    ReporteSocios socio = new ReporteSocios();
                    socio.setLocationRelativeTo(null);
                    socio.getContentPane().setBackground(Color.decode("#7329ab"));
                    socio.setVisible(true);
                    break;           
            } // fin de switch
            this.dispose();
        }

        else
        {
            Funciones.imprimirMsj("Lo sentimos el usuario o contraseña son incorrectos");
        }
      }

} // fin de clase Login
