/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 22/03/2010, 01:51:14 PM
 */

package zolbee2;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author roberto
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuReportesFechas = new javax.swing.JMenuItem();
        MenuReportesEmpleados = new javax.swing.JMenuItem();
        MenuReporteSocios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zolbee2.Zolbee2App.class).getContext().getResourceMap(Menu.class);
        setTitle(resourceMap.getString("Menu.title")); // NOI18N
        setName("Menu"); // NOI18N
        setResizable(false);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(resourceMap.getIcon("jMenuItem3.icon")); // NOI18N
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mostrarConsumo(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText(resourceMap.getString("jMenu3.text")); // NOI18N
        jMenu3.setName("jMenu3"); // NOI18N

        MenuReportesFechas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        MenuReportesFechas.setText(resourceMap.getString("MenuReportesFechas.text")); // NOI18N
        MenuReportesFechas.setName("MenuReportesFechas"); // NOI18N
        MenuReportesFechas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuReportesFechasMouseReleased(evt);
            }
        });
        MenuReportesFechas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MenuReportesFechasKeyReleased(evt);
            }
        });
        jMenu3.add(MenuReportesFechas);

        MenuReportesEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuReportesEmpleados.setText(resourceMap.getString("MenuReportesEmpleados.text")); // NOI18N
        MenuReportesEmpleados.setName("MenuReportesEmpleados"); // NOI18N
        MenuReportesEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuReportesEmpleadosMouseReleased(evt);
            }
        });
        MenuReportesEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MenuReportesEmpleadosKeyReleased(evt);
            }
        });
        jMenu3.add(MenuReportesEmpleados);

        MenuReporteSocios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuReporteSocios.setText(resourceMap.getString("MenuReporteSocios.text")); // NOI18N
        MenuReporteSocios.setName("MenuReporteSocios"); // NOI18N
        MenuReporteSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuReporteSociosMouseReleased(evt);
            }
        });
        MenuReporteSocios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MenuReporteSociosKeyReleased(evt);
            }
        });
        jMenu3.add(MenuReporteSocios);

        jMenuBar1.add(jMenu3);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenu2.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1MouseReleased

    private void mostrarConsumo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarConsumo
        // TODO add your handling code here:
        /*Consumos consumo = new Consumos ();
        consumo.setLocationRelativeTo(null);
        consumo.getContentPane().setBackground(Color.decode("#7329ab"));
        consumo.setVisible(true);*/
        LoginEmpleado loguarseEmpleado = new LoginEmpleado ();
        loguarseEmpleado.setLocationRelativeTo(null);
        loguarseEmpleado.getContentPane().setBackground(Color.decode("#7329ab"));
        loguarseEmpleado.setVisible(true);




    }//GEN-LAST:event_mostrarConsumo

    private void MenuReportesFechasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuReportesFechasMouseReleased
        // TODO add your handling code here:


        LoginReportes loguarseAdmin = new LoginReportes(1);
        loguarseAdmin.setLocationRelativeTo(null);
        loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
        loguarseAdmin.setVisible(true);
        /*ReportesFecha fecha = new ReportesFecha ();
        fecha.setLocationRelativeTo(null);
        fecha.getContentPane().setBackground(Color.decode("#7329ab"));
        fecha.setVisible(true);*/






    }//GEN-LAST:event_MenuReportesFechasMouseReleased

    private void MenuReportesEmpleadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuReportesEmpleadosMouseReleased
        // TODO add your handling code here:
         LoginReportes loguarseAdmin = new LoginReportes(2);
         loguarseAdmin.setLocationRelativeTo(null);
         loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
         loguarseAdmin.setVisible(true);

        /*ReportesEmpleado empleado = new ReportesEmpleado ();
        empleado.setLocationRelativeTo(null);
        empleado.getContentPane().setBackground(Color.decode("#7329ab"));
        empleado.setVisible(true);*/
    }//GEN-LAST:event_MenuReportesEmpleadosMouseReleased

    private void MenuReporteSociosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuReporteSociosMouseReleased
        // TODO add your handling code here:
         LoginReportes loguarseAdmin = new LoginReportes(3);
         loguarseAdmin.setLocationRelativeTo(null);
         loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
         loguarseAdmin.setVisible(true);
         /*ReporteSocios socio = new ReporteSocios();
         socio.setLocationRelativeTo(null);
         socio.getContentPane().setBackground(Color.decode("#7329ab"));
         socio.setVisible(true);*/

    }//GEN-LAST:event_MenuReporteSociosMouseReleased

    private void MenuReportesFechasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuReportesFechasKeyReleased
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
         LoginReportes loguarseAdmin = new LoginReportes(1);
         loguarseAdmin.setLocationRelativeTo(null);
         loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
         loguarseAdmin.setVisible(true);
      }


    }//GEN-LAST:event_MenuReportesFechasKeyReleased

    private void MenuReportesEmpleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuReportesEmpleadosKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
         LoginReportes loguarseAdmin = new LoginReportes(2);
         loguarseAdmin.setLocationRelativeTo(null);
         loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
         loguarseAdmin.setVisible(true);
      }
    }//GEN-LAST:event_MenuReportesEmpleadosKeyReleased

    private void MenuReporteSociosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuReporteSociosKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
         LoginReportes loguarseAdmin = new LoginReportes(3);
         loguarseAdmin.setLocationRelativeTo(null);
         loguarseAdmin.getContentPane().setBackground(Color.decode("#7329ab"));
         loguarseAdmin.setVisible(true);
      }
    }//GEN-LAST:event_MenuReporteSociosKeyReleased

    /**
    * @param args the command line argument
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuReporteSocios;
    private javax.swing.JMenuItem MenuReportesEmpleados;
    private javax.swing.JMenuItem MenuReportesFechas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

}
