/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SucursalesConf.java
 *
 * Created on 18/03/2010, 05:13:21 PM
 */

package zolbee2;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.lang.String;

/**
 *
 * @author roberto
 */
public class SucursalesConf extends javax.swing.JFrame {

    

    /** Creates new form SucursalesConf */
    public SucursalesConf() {
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vSucursalesConf = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vUsuarioSistem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vPaswSistem = new javax.swing.JPasswordField();
        vPaswSistemVer = new javax.swing.JPasswordField();
        bGuardarConf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zolbee2.Zolbee2App.class).getContext().getResourceMap(SucursalesConf.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                abrirFormSucursalesConf(evt);
            }
        });

        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        vSucursalesConf.setName("vSucursalesConf"); // NOI18N

        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        vUsuarioSistem.setText(resourceMap.getString("vUsuarioSistem.text")); // NOI18N
        vUsuarioSistem.setName("vUsuarioSistem"); // NOI18N
        vUsuarioSistem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarTextUsuario(evt);
            }
        });

        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        vPaswSistem.setText(resourceMap.getString("vPaswSistem.text")); // NOI18N
        vPaswSistem.setName("vPaswSistem"); // NOI18N
        vPaswSistem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarPass(evt);
            }
        });

        vPaswSistemVer.setText(resourceMap.getString("vPaswSistemVer.text")); // NOI18N
        vPaswSistemVer.setName("vPaswSistemVer"); // NOI18N
        vPaswSistemVer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarPas2(evt);
            }
        });

        bGuardarConf.setText(resourceMap.getString("bGuardarConf.text")); // NOI18N
        bGuardarConf.setName("bGuardarConf"); // NOI18N
        bGuardarConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bGuardarConfMouseReleased(evt);
            }
        });
        bGuardarConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bGuardarConfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vSucursalesConf, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vPaswSistemVer)
                        .addComponent(vPaswSistem)
                        .addComponent(vUsuarioSistem, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(bGuardarConf)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vSucursalesConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(vUsuarioSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vPaswSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vPaswSistemVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(bGuardarConf)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirFormSucursalesConf(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_abrirFormSucursalesConf
        // TODO add your handling code here:
        
        Funciones.llenarSucursalesList();
    }//GEN-LAST:event_abrirFormSucursalesConf

    private void validarTextUsuario(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarTextUsuario
        // TODO add your handling code here:

        String usuario = vUsuarioSistem.getText();
        //System.out.println(usuario);
        Funciones funcion = new Funciones ();

        funcion.validarTextCN(usuario);
        if(funcion.bandera==1)
        {
            vUsuarioSistem.setText(funcion.subcadena);

        }
 
    


    }//GEN-LAST:event_validarTextUsuario

    private void validarPass(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarPass
       // TODO add your handling code here:
       String pass = vPaswSistem.getText();
        //System.out.println(usuario);
        Funciones funcion = new Funciones ();

        funcion.validarTextCN(pass);
        if(funcion.bandera==1)
        {
            vPaswSistem.setText(funcion.subcadena);

        }

         
    }//GEN-LAST:event_validarPass

    private void validarPas2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarPas2
        // TODO add your handling code here:
        String pass = vPaswSistemVer.getText();
        //System.out.println(usuario);
        Funciones funcion = new Funciones ();

        funcion.validarTextCN(pass);
        if(funcion.bandera==1)
        {
            vPaswSistemVer.setText(funcion.subcadena);

        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            guardarConf();
         } // fin de if
         

    }//GEN-LAST:event_validarPas2

    private void bGuardarConfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bGuardarConfKeyReleased
        // TODO add your handling code here:
        guardarConf();
    }//GEN-LAST:event_bGuardarConfKeyReleased

    private void bGuardarConfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarConfMouseReleased
        // TODO add your handling code here:
        guardarConf();
    }//GEN-LAST:event_bGuardarConfMouseReleased

    /**
    * @param args the command line arguments
    */
     private void comboList() {

        jLabel1 = new javax.swing.JLabel();
        bGuardarConf = new javax.swing.JButton();
        vSucursalesConf = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zolbee2.Zolbee2App.class).getContext().getResourceMap(SucursalesConf.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        bGuardarConf.setText(resourceMap.getString("jButton1.text")); // NOI18N
        bGuardarConf.setName("jButton1"); // NOI18N

        vSucursalesConf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vSucursalesConf.setName("vSucursalesConf"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vSucursalesConf, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bGuardarConf)
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarConf)
                    .addComponent(vSucursalesConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>





    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucursalesConf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarConf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JPasswordField vPaswSistem;
    public static javax.swing.JPasswordField vPaswSistemVer;
    public static javax.swing.JComboBox vSucursalesConf;
    public static javax.swing.JTextField vUsuarioSistem;
    // End of variables declaration//GEN-END:variables



   public void guardarConf()
    {
        String usr = vUsuarioSistem.getText();
        String pas = vPaswSistem.getText();
        String pas2 = vPaswSistemVer.getText();
        Object suc = vSucursalesConf.getSelectedItem();
        int b = 0;
        String array[] = null;

        String suc2  = suc.toString();
        array = suc2.split("-");

            EscribeFichero escribirFichero = new EscribeFichero();

           if(usr.equals(""))
           {
              b=1;
           }
           if(pas.equals(""))
           {
              b=1;
           }
           if(pas2.equals(""))
           {
              b=1;
           }

           if(b==0)
           {

             if(pas.equals(pas2))
             {
                escribirFichero.determinarFichero(usr, pas, array);
                Menu menu = new Menu();
                menu.setLocationRelativeTo(null);
                menu.getContentPane().setBackground(Color.decode("#7329ab"));
                
                 //lo hacemos visible
                 menu.setVisible(true);
                 //maximizamos la pantalla
                 //f1.setExtendedState(f1.getExtendedState()|f1.MAXIMIZED_BOTH);
                 this.dispose();

             }
             else
             {
                Funciones.imprimirMsj("La verificación de la contraseña no coincide");
             }
          } // fin de if b==0

          else if(b==1)
          {
             Funciones.imprimirMsj("Lo siento necesita llenar todos los campos");
          }


    } // fin de método guardarConf

} // fin de la clase SucursalesConf
